PRODUCT_KEYWORDS = [
    'buy', 'price', 'add to cart', 'product details', 'specs',
    'purchase', 'shop', 'order', 'shipping', 'stock',
]
GOOG_DISCARD_KEYWORDS = {
    '.pdf'
    'northerntool',
    'wish',
    'saksfifthavenue',
    'trademe',
    'foxnews',
    'skinstore',
    'youtube',
    'lookfantastic',
    'asos',
    'homebase',
    'oreillyauto',
    'comment',
    'notebookcheck',
    'toolstation',
    'mercadolibre',
    'wikipedia',
    'samash',
    'tomshardware',
    'vk',
    'cnet',
    'allegro',
    'fruugo',
    'advance auto',
    'theperfumeshop',
    'twitter',
    'walmart',
    'b&h',
    'joom',
    'samsclub',
    'costco',
    'bathandbodyworks',
    'menards',
    'forbes',
    'autoanything',
    'advanceautoparts',
    'androidauthority',
    'tokopedia',
    '9to5mac',
    'ebay',
    'gumtree',
    'feelunique',
    'harborfreight',
    'boohoo',
    'overstock',
    'businessinsider',
    'digitaltrends',
    'techcrunch',
    'ulta',
    'gsmarena',
    'homedepot',
    'thenextweb',
    'wayfair',
    'bloomingdales',
    'engadget',
    'linkedin',
    'instagram',
    'barbersupply',
    'home depot',
    'qvc',
    'guitarcenter',
    'wickes',
    'ifixit',
    'thetelegraph',
    'shopee',
    'thomann',
    'musiciansfriend',
    'acehardware',
    'acetool',
    'beautybay',
    'johnlewis',
    'autozone',
    'laptopmag',
    'screwfix',
    'jiji',
    'theartofshaving',
    'beardbrand',
    'kogan',
    'techradar',
    'pepboys',
    'tractorsupply',
    'crutchfield',
    'reddit',
    'vijay sales',
    'slashgear',
    'target.',
    'macy',
    'baidu',
    'petvalu',
    'kmart',
    'myntra',
    'zalando',
    'aljazeera',
    'tmall',
    'wirecutter',
    'vipshop',
    'cnbc',
    'nordstrom',
    'bonanza',
    'reilly',
    'bbc',
    'aliexpress',
    'harrods',
    'tiktok',
    'petco',
    'sephora',
    'etsy',
    'jd.com',
    'machinemart',
    'sears',
    'bedbathbeyond',
    'cdiscount',
    'lazada',
    'cultbeauty',
    'issue',
    'weibo',
    'community',
    'alibaba',
    'houzz',
    'neimanmarcus',
    'croma',
    'bestbuy',
    'groominglounge',
    'nykaa',
    'quora',
    'b2w',
    'bloomberg',
    'craigslist',
    'adorama',
    'pinterest',
    'flipkart',
    'newegg',
    'petsmart',
    'anandtech',
    'support',
    'gosupps',
    'hsn',
    'monoprice',
    'reliance digital',
    'snapchat',
    'canadiantire',
    'latimes',
    'theguardian',
    'q&a',
    'snapdeal',
    'theverge',
    'nymag',
    'huffpost',
    'help',
    'petsuppliesplus',
    'overview',
    'gizmodo',
    'dpreview',
    'debenhams',
    'fragrancenet',
    'facebook',
    'sweetwater',
    'tumblr',
    'macrumors',
    'gearbest',
    'phonearena',
    'pcmag',
    'justanswer',
    'harveynichols',
    'truevalue',
    'zazzle',
    'adorebeauty',
    'discussion',
    'nytimes',
    'daraz',
    'dermstore',
    'lightinthebox',
    'cnn',
    'rakuten',
    'mensbiz',
    'thebodyshop',
    'problem',
    'review',
    'lowes',
    'marketwatch',
    'forum',
    'taobao',
    'complaint',
    'flickr',
    'chewy',
    'summitracing',
    'shopall',
    'shop-all',
    'allproduct',
    'all-product',
    'catalog',
    'berdaya',
    'tcsgrenada',
    'angelaricardo',
    'tourist',
    'laurencosenza',
    'moglix',
    'ohfeliz',
    'shescribe',
    'heureka',
    'beautycarechoice',
    'blog',
    'thouqi',
    'kingdomofbeauty',
    'shavers.co.uk',
    'tabletmonkeys',
    'liaow',
    'giztop',
    'kutnbeauty',
    'safeandsoundhq',
    'manuals.plus',
    'minusthemarble',
    'makeupandbeautyblog',
    'tejar',
    'mybeautybunny',
    'bonboncosmetics',
    'computerdealsdirect',
    'edgeup',
    'laptopchargers.co',
    'avadirect',
    'shavershop',
    'salonbackbar',
    'beautystoponline',
    'brandsmartusa',
    'eraj',
    '4gltemall',
    'esim.me',
    'boddess',
    'bikerumor',
    'pandorabeauty',
    'kindlyunspoken',
    'maquibeauty',
    'theinventory',
    'platinumdental',
    'denmat',
    'smiledirectclub',
    'the-ebook-reader',
    'kriplus',
    'telquestintl',
    'corporatearmor',
    'hulanetworks',
    'westwardsales',
    'worldsim',
    'electropunt',
    'appliancentre',
    'gadgets360',
    'ajapplianceinc',
    'electricity.gg',
    'eros.ae',
    'senq',
    'us-appliance.com',
    'borshch',
    'instok',
    'fcfarmandhome',
    'petra',
    'pcxssolution',
    'macsales',
    'americastestkitchen',
    'athriftymom',
    'younghouselove',
    'wellbots',
    'delawarevalleyappliance',
    'billandrodsappliance',
    'press.',
    'pc-pitstop',
    'servethehome',
    'vplak',
    'theappliancedepotoutlet',
    'gooddealsappliances',
    'big-georges',
    'ubuy',
    'webstaurantstore',
    'shopheralds',
    'gringerandsons',
    'manymanual',
    'staples',
    'mrcentre',
    'appliancesuperstore',
    'colonialappliance',
    'malabs',
    'aphnetworks',
    'surlatable',
    'quenchessential',
    '1stincoffee',
    'fordsbasement',
    'apps.apple',
    'crateandbarrel',
    'zabars',
    'bigtools',
    'takealot',
    'sylvane',
    'purahome',
    'allergybuyersclub',
    'theappliancecentreni',
    'provantage',
    'jarvisappliance',
    'weaverappliance',
    'katom',
    'pcrichard',
    'rosners',
    'life360',
    'ldlc',
    'motionmedia',
    'rockler',
    'acmetools',
    'ultimatetool',
    'toolstoday',
    'redmondmachinery',
    'ustooldepot',
    'highlandwoodworking',
    'aaabrasives',
    'compressorworldcanada',
    'primadian',
    'compressedairsystems',
    'sand-blaster',
    'compressorpro',
    'toolsandmore',
    'businessgateway',
    'toolsmartusa',
    'paintsprayersplus',
    'sprayequipment.com',
    'eahindustrial',
    'hvlp',
    'sprayandmore',
    'jbtool',
    'kbtool',
    'picclick',
    'sparesonweb',
    'ppe-pressure-washer-part',
    'cpooutlets',
    'snowjoe',
    'totaltools',
    'alliedhomecenter',
    'misterworker',
    'carbideprocessors',
    'bowerstool',
    'lawnland',
    'powerequipmentwarehouse',
    'hivefly',
    'russopower',
    'tricountypowerequipmentinc',
    'greenindustrypros',
    'gandlequipment',
    'mtdpart',
    'justprotools',
    'gearwrench',
    'tikweld',
    'gz-supplies',
    'emisupply',
    'starsales',
    'toolnation',
    'tts-products',
    'shelllumber',
    'ustoolandfastener',
    'highlandwoodworking',
    'bodyshopbusiness',
    'get-manual',
    'get_manual',
    'abrasivesupply',
    'cwhaydenonline',
    'toolmarts',
    'mile-x',
    'burnstools',
    'paulbhardware',
    'gotopac',
    'justlawnmowers',
    'sparetoolparts',
    'tooled-up',
    'sepw',
    'partswarehouse',
    'outdoorpowerdirect',
    'mowdirect',
    'melbournetoolsale',
    'appraiserslaser',
    'testers',
    'industrialladder',
    'engineersupply',
    'tigersupplies',
    'lighttoolsupply',
    'meterland',
    'vpcivil',
    'thegangbox',
    'roundhousepowersports',
    'bemotorsports',
    'gruettspowercenter',
    'aeoutdoorpower',
    'lawnbarn',
    'hikoki-powertools',
    'housebecominghome',
    'woodpeck',
    'bodyshopbusiness',
    'poolvacparts',
    'poolsupplydelivery',
    'funkyleisure',
    'campchef.com',
    'girlcamper',
    'spraywell',
    'amickssuperstore',
    'wallerspowerequipment',
    'backcountry',
    'davidgraymedia',
    'ems.com',
    'ukcampsite',
    'clean.direct',
    'hardwareandtools.com',
    'thewoodturningstore',
    'tacklifetool',
    'ukplanttool',
    'coloradostandby',
    'bestaircompressor',
    'machinio',
    'dripworks',
    'sprinklerwarehouse',
    'campingworld',
    'greatlakesace',
    'grillio',
    'bbqs2u',
    'bbqgrills',
    'blackhillsfireplace',
    'bbq-authority',
    'kickassgrills',
    'libertymountain',
    'hngematte',
    'authenteak',
    'toolsandtoys',
    'liveworkwander',
    'kickstarter',
    'cordlesspower.co',
    'powertoolworld',
    'precisionsmallengines',
    'greenacrespowersports',
    'gautreauxsoutdoorpower',
    'bestmowerstore',
    'texastractorcountry',
    'leestools',
    'sprayequipment',
    'lesliespool',
    'epicpoolsupply',
    'philmontscoutranch',
    'asedeals',
    'equipsupply',
    'brandsmartusa'
}
UNAVAILABLE_KEYWORDS = [
    '404', '403', '503',
    'oops', 'uh oh',
    'forbidden',
    'server is down',
    "doesn't exist",
    "does not exist",
    "can't find",
    "cannot find",
    "can't seem to find",
    "cannot seem to find",
    'nothing was found',
    'not found',
    'no seller found',
    'no sellers found',
    'out of stock',
    'no stock',
    'not in stock',
    'depleted stock',
    'awaiting stock',
    'no longer stocked',
    'exhausted stock',
    'out of inventory',
    'sold out',
    'ceased production',
    'no longer selling',
    'stopped selling',
    'out of production',
    'ended production',
    'no longer in production',
    'discontinue',
    'phased out',
    'no longer available',
    'retired product',
    'end of life',
    'backorder',
    'unavailable',
    'not available',
    'suspended sales',
    'not for sale',
    'off the market',
    'production halted',
    'withdrawn',
    'archived product',
    'supply exhausted',
    'not currently available',
    '找不到',
    '无法找到',
    '已被移除',
    'timed out',
    'pardon our interruption',
]
